Small fixes I added to get scripts working for make-release. Mostly error checking, switching to master before we tag and updated command to get current branch to work with older Mac git as well as new ones

diff --git a/bin/make-repo-release b/bin/make-repo-release
--- a/bin/make-repo-release
+++ b/bin/make-repo-release
@@ -82,7 +82,7 @@ if [[ -z "$VERSION" || -z "$relnum" ]]; then
 fi
 
 # Check current branch against version: must be the same
-BRANCH=`git branch --show-current`
+BRANCH=`git branch | grep \* | cut -d ' ' -f2`
 if [[ "$force" == "false" && "$VERSION" != "$BRANCH" ]]; then
     error "I cannot make the $VERSION release from branch $BRANCH"
 fi
@@ -296,13 +296,20 @@ else
         GITMSG="$GITMSG - DEB $DEB_VERSION"
     fi
     git commit ${commit_a} -m "$GITMSG"
+    
+    #switch to master and merge
+    git checkout master
+    git merge --no-edit $BRANCH
+    if [ ! $? -eq 0 ]; then
+        error "Unable to merge $BRANCH into master, skipping tags"
+    fi
+    
     if [ -n "$RPM_VERSION" ]; then
         git tag "${GIT_TAG}"
     fi
     if [ -n "$DEB_VERSION" ]; then
         git tag "${DEBIAN_TAG}"
     fi
-    echo
     echo "If you're happy with the commit and tag(s) above, you just need to push that away!"
 fi
 
